openapi: 3.0.3
info:
  title: Random Commerce Mock API
  version: 1.0.0
  description: Randomized mock API for dynamic testing.
servers:
  - url: http://127.0.0.1:8001
paths:
  /customers:
    post:
      summary: Create customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        "201":
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

  /customers/{customerId}:
    get:
      summary: Get customer by id
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Customer payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

  /orders:
    post:
      summary: Create order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        "200":
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      summary: Get order by id
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

  /orders/{orderId}/status:
    patch:
      summary: Update order status
      operationId: updateOrderStatus
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [status]
              properties:
                status:
                  type: string
                  enum: [pending, confirmed, packed, shipped, delivered, cancelled]
      responses:
        "200":
          description: Order status payload
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [orderId, status, updatedAt]
                properties:
                  orderId:
                    type: string
                  status:
                    type: string
                    enum: [pending, confirmed, packed, shipped, delivered, cancelled]
                  updatedAt:
                    type: string
                    format: date-time

  /catalog/{sku}:
    get:
      summary: Get catalog item
      operationId: getCatalogItem
      parameters:
        - name: sku
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Catalog payload
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [sku, title, price, stock]
                properties:
                  sku:
                    type: string
                  title:
                    type: string
                  price:
                    type: number
                    format: float
                  stock:
                    type: integer
                    minimum: 0

  /tickets:
    post:
      summary: Create support ticket
      operationId: createTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [orderId, issueType, notes]
              properties:
                orderId:
                  type: string
                issueType:
                  type: string
                  enum: [delay, damaged, billing, other]
                notes:
                  type: string
      responses:
        "200":
          description: Ticket payload
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [ticketId, orderId, issueType, severity, status]
                properties:
                  ticketId:
                    type: string
                  orderId:
                    type: string
                  issueType:
                    type: string
                    enum: [delay, damaged, billing, other]
                  severity:
                    type: string
                    enum: [low, medium, high]
                  status:
                    type: string
                    enum: [open, investigating, resolved]

  /health:
    get:
      summary: Service health
      operationId: serviceHealth
      responses:
        "200":
          description: Health payload
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                required: [service, status, timestamp]
                properties:
                  service:
                    type: string
                  status:
                    type: string
                    enum: [ok, degraded]
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    CreateCustomerRequest:
      type: object
      additionalProperties: false
      required: [name, email]
      properties:
        name:
          type: string
          minLength: 2
        email:
          type: string
          format: email
        tier:
          type: string
          enum: [bronze, silver, gold]

    Customer:
      type: object
      additionalProperties: false
      required: [customerId, name, email, tier, status, createdAt]
      properties:
        customerId:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        tier:
          type: string
          enum: [bronze, silver, gold]
        status:
          type: string
          enum: [active, inactive]
        createdAt:
          type: string
          format: date-time

    CreateOrderRequest:
      type: object
      additionalProperties: false
      required: [customerId, currency, items]
      properties:
        customerId:
          type: string
        currency:
          type: string
          enum: [USD, EUR, INR]
        items:
          type: array
          minItems: 1
          items:
            type: object
            additionalProperties: false
            required: [sku, quantity]
            properties:
              sku:
                type: string
              quantity:
                type: integer
                minimum: 1
        priority:
          type: string
          enum: [low, normal, high]

    Order:
      type: object
      additionalProperties: false
      required: [orderId, customerId, currency, totalAmount, status, estimatedDelivery]
      properties:
        orderId:
          type: string
        customerId:
          type: string
        currency:
          type: string
          enum: [USD, EUR, INR]
        totalAmount:
          type: number
          format: float
        status:
          type: string
          enum: [pending, confirmed, packed, shipped, delivered, cancelled]
        estimatedDelivery:
          type: string
          format: date-time
